[package]
name = "matcher-derive"
version = "0.2.0"
edition = "2021"

[lib]
proc-macro = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.37"
syn = { version = "2.0.77", features = ["full", "derive"] }
matcher-derive-impl = "0.2.0"
