[package]
name = "matcher-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
bollard-next = "0.15.4"
clap = { version = "4.4.9", features = ["derive"] }
futures-util = "0.3.29"
reqwest = { features = ["json"], version = "0.11.22" }
serde = "1.0.193"
serde_json = "1.0.108"
serde_yaml = "0.9.27"
tokio = { version = "1.34.0", features = ["full"] }
url = "2.5.0"
openssl = { version = "*", features = ["vendored"] }
matcher-derive = "^0.1.0"
matcher-derive-impl = { version = "^0.1.0" }

[profile.release]
strip = true
opt-level = "z"
codegen-units = 1
