[package]
name = "docker-apprise-connector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.89"
bollard-next = "0.16.1"
clap = { version = "4.5.18", features = ["derive"] }
futures-util = "0.3.30"
reqwest = { features = ["json"], version = "0.12.7" }
serde = "1.0.210"
serde_json = "1.0.128"
serde_yaml = "0.9.34"
tokio = { version = "1.40.0", features = ["full"] }
url = "2.5.2"
openssl = { version = "*", features = ["vendored"] }
matcher-derive = { path = "../matcher-derive" }
matcher-derive-impl = { path = "../matcher-derive-impl" }

[profile.release]
strip = true
opt-level = "z"
codegen-units = 1
