name: "Bump version"

on:
  workflow_dispatch:

jobs:
  create-tag:
    name: "Bump version"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 9999
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Install dev deps"
        run: |
          SKIP_GIT_HOOKS=true ./scripts/init-dev-env.sh

      - name: "Bump versions"
        id: bump-version
        run: |
          ./scripts/bump-version.sh matcher-derive-impl
          ./scripts/bump-version.sh matcher-derive
          echo NEED_PUSH=`if [[ `git status --porcelain` ]]; then echo "true"; fi` >> $GITHUB_OUTPUT

      - name: "Commit release"
        # Don't run again on already pushed auto commit. Don't run on pull request events.
        if: steps.bump-version.outputs.NEED_PUSH == true
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit --no-verify -a -m "Release `git tag --points-at HEAD`"

      - name: Push changes
        if: steps.bump-version.outputs.NEED_PUSH == true
        uses: anonkey/github-push-action@feat/no-verify-flag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
          tags: true
