name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - matcher-derive-[0-9]+.[0-9]+.[0-9]+
      - matcher-derive-impl-[0-9]+.[0-9]+.[0-9]+

env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_RELEASE_CODEGEN_UNITS: 1
  CARGO_PROFILE_RELEASE_LTO: true
  CARGO_PROFILE_RELEASE_OPT_LEVEL: "s"
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings"
  RUSTUP_MAX_RETRIES: 10

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Parse version
        id: vars
        run: echo "package=`echo ${GITHUB_REF#refs/*/}" | sed -r 's/-([0-9]+.?)+//g'` version=`echo ${GITHUB_REF#refs/*/}" | sed -r 's/(([a-z]+)-)+(([0-9]+.?)+)/\3/'` >> $GITHUB_OUTPUT

      - uses: taiki-e/create-gh-release-action@v1.8.0
        with:
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
          changelog: ./packages/matcher-derive/CHANGELOG.md
          prefix: ${{ steps.bump-version.outputs.package }}-

  # upload-crates-io:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - run: cargo publish --dry-run --token ${CRATES_TOKEN}
  #       env:
  #         CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
